language: rust

cache: cargo

git:
  depth: 1

install: cargo build --release

script: true

deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file_glob: true
  file: "./target/release/license-gen"
  skip_cleanup: true
  on:
    tags: true

notifications:
  email:
    on_success: never
